### ISSUE TITLE
Raw Image Editor

### ISSUE THREAD

**Issue by drashna** [joric/qle#1]
Instead of having a set size based on the keyboard, it would be nice to have a number of options, or even a "custom" option. Eg: 

* 128x32
* 128x64
* 64x32
* etc

This will allow a lot more customization of the OLED screen and the possibility of doing animations that are not full screen.

**Comment by joric** [comment]
They break at 128 boundary aren't they? There are no line breaks and most screens are 128 pixels wide. Are you suggesting making it 64 pixel wide screens compatible? Have you seen those screens?

**Comment by drashna** [comment]
For the raw stuff, you don't have to use the whole screen.  You can use a section.  And you can use the "move cursor" commands to write to specific sections too. 

So having the option

**Comment by kageurufu** [comment]
I'm working on a new RGBKB board with a STM32 chip, and we're talking about storing full animations in the font. I "resized" the image by pasting a bunch of 0x00 at the end of the font to get to 10 rows, but having either a dropdown, or a number input for rows/cols of font data would be nice for that.
